### ISSUE TITLE
`-comment` failed

### ISSUE THREAD

**Issue by askfiy** [uga-rosa/translate.nvim#26] opened 2022-09-29 03:57 UTC
command:

```
Translate ZH -source=EN -output=floating -comment
```

When I use the default configuration, its error is:

![image](https://user-images.githubusercontent.com/81478335/192934877-32a56abd-232f-45fc-928c-be96ac8d8e75.png)

My minimized init.lua file:

```
vim.opt.termguicolors = true
vim.opt.cursorline = true
vim.opt.number = true
vim.g.mapleader = " "

vim.opt.runtimepath:append("~/.local/share/nvim/site/pack/packer/opt/translate.nvim")

vim.cmd([[runtime! after/plugin/*.lua]])
```

When I'm not using the minimized file it throws another error:

![image](https://user-images.githubusercontent.com/81478335/192935165-4021aef4-63f9-40da-b848-4bd3cc6b8c28.png)

Below is my configuration：

```
{
  default = {
      command = "google",
      output = "floating",
      parse_before = "trim",
  },
  replace_symbols = {
      google = {},
      deepl_pro = {},
      deepl_free = {},
      translate_shell = {},
  },
}
```

**Comment by uga-rosa** [comment] 2022-09-29 10:20
Can you also provide a minimum text you are trying to translate?

**Comment by uga-rosa** [comment] 2022-09-29 10:24
Looks like the vim.lsp spec has changed.
Which version neovim you use?

**Comment by askfiy** [comment] 2022-09-29 10:24
> Looks like the vim.lsp spec has changed. Which version neovim you use?

$ nv --version
NVIM v0.8.0-dev-1183-ge6c214033

**Comment by askfiy** [comment] 2022-10-06 09:29
> > Can you also provide a minimum text you are trying to translate?
> 
> I can't reproduce it in my environment, so please let me know what kind of file it happens with.

Python File: 

```
    """
    This is Block Comment ...
    1. line 1
    2. line 2
    3. line 3
    """
```

TypeScript FIle:

```
/*
  This is Block Comment ...
  1. line 1
  2. line 2
  3. line 3
*/
```

```

**Comment by uga-rosa** [comment] 2022-10-06 14:20
It should be fixed. Please try it.

**Closed** 2022-10-06 14:19 UTC

**Comment by uga-rosa** [comment] 2022-10-06 15:48
I can't reproduce it.
![image](https://user-images.githubusercontent.com/82267684/194358501-8ed667fb-31de-411e-8804-a5fd45c4b661.png)
Maybe a bug specific to `-command=google`.
